### ISSUE TITLE
Where is dataset.tsv?

### ISSUE THREAD

**Issue by ragvri** [deepanshu1995/Emotion-Prediction#3]
In the file `create_mapping.py`, you seem to be making use of a file named `dataset.tsv`. I cannot find this file in the repository.

**Comment by deepanshu1995** [comment]
Yeah because we have made only tweet id's public not the tweets. Just go
through paper and ReadMe on github. You can easily understand that.

Thanks,
Deepanshu Vijay

**Comment by ragvri** [comment]
Mailed you.

**Comment by ragvri** [comment]
In the readme, you mentioned that person can mail you for the dataset. I have sent you a mail :)
